### ISSUE TITLE
AMD

### ISSUE THREAD

**Issue by frode88** [tellor-io/TellorMiner#124]
Hi,
Dos this miner work for AMDs?
thank you

**Comment by themandalore** [comment]
Hi @frode88 , it should.  Feel free to hit me up on telegram (@the_fett) and I'll help you debug (or feel free to post in the discord/miner channels, the groups are very helpful and quick)

**Comment by frode88** [comment]
Ok. I will fire up some rx 570 card on the pool and see. I will dm on telegram if i need help. Thank you alot
