### ISSUE TITLE
About Stratum

### ISSUE THREAD

**Issue by frode88** [tellor-io/TellorMiner#127]
Hi.
Will this Miner Support Stratum in near future?
Thank you.

**Comment by themandalore** [comment]
It's definitely not on our immediate priority list, but I know it will eventually get there.  (so no as a quick answer)

**Comment by frode88** [comment]
Ok, thank you. We will wait until stratum in place before releasing the pool we made. Have a nice day.

**Comment by themandalore** [comment]
Cool.  I've actually never implemented support for stratum before, so if you want to build it out, happy to have a call and support you in the build

**Comment by frode88** [comment]
Thank you. We will get in touch when we secured the 5K tellor.
