### ISSUE TITLE
PSR ID 25 not calculated properly.

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TellorMiner#178]
Hi  ,  i may have found a bug in V1.  For requestid 25,     if  the exchange api returns  like this 
[[1599782400000,"0.99970000","1.00100000","0.99950000","1.00000000","17708475.76000000",1599868799999,"17708852.00109300",12301,"8172912.93000000","8173387.20382900","0"]]     ,  trbminer gets the price of index 4,  which  should be   "1.00000000".  But after trbminer analyzes the response , it will return 0.
If the price of index 4 is not exactly equals to 1  ,   trbminer can the right value.

From Discord channel

**Comment by krasi-georgiev** [comment]
This will be a good use case to write an e2e tests for this.
