### ISSUE TITLE
Containerize TellorMiner

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/TellorMiner#230]
Create a `Dockerfile` and `docker-compose.yaml` for running the TellorMiner using Docker

**Comment by krasi-georgiev** [comment]
We have been discussing this and it would be an easy thing to add and auto build with the CI.

Can you explain how and where are you using the docker container?

**Comment by mikeghen** [comment]
I run everything in Kubernetes so everything has to be containerized, its also just how I run everything on my localhost since I don't want to install a bunch of things

**Comment by krasi-georgiev** [comment]
yep I had the same thought few days ago and it will be an easy thing to add, just wasn't sure if people will actually use it. Now that I know will put in the TODO list. Thanks for the feedback.
