### ISSUE TITLE
Remove risky submission scenario 

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/TellorMiner#245]
I just saw this warning while reviewing something else. The miner should under no circumstances be submitting invalid data, I understand the need to prevent someone from spamming unused request IDs, but the proper way to handle those cases should be using `manualData.json`, not coding in a scenario where the miner submits potentially invalid data.

https://github.com/tellor-io/TellorMiner/blob/e97654525c2d34f45979e045311ec9cdf7cf23ad/pkg/pow/solutionHandler.go#L58

**Comment by mikeghen** [comment]
```
challenge.RequestIDs[i].Uint64() > 53
```
Feels like this will be a source of error once requests start getting added

**Comment by krasi-georgiev** [comment]
Thanks for reporting this will look into it. @themandalore can probably add some more context on why is this coded like this.

**Comment by themandalore** [comment]
yup, fixed it here: https://github.com/tellor-io/TellorMiner/pull/244/files

**Comment by krasi-georgiev** [comment]
@themandalore what about this line : `challenge.RequestIDs[i].Uint64() > 53` what is the logic behind this?

**Comment by mikeghen** [comment]
The last request ID was 53, sometimes people submit requests for other ids (e.g. 64) and no miners will submit, so this locks up the network, this was put in to patch that, but it could cause problems in the future if a miner doesn't increase the ID once more requests are added
