### ISSUE TITLE
Rinkeby Submission Errors - "replacement transaction underpriced", "nonce too low"

### ISSUE THREAD

**Issue by Spuddyminer** [tellor-io/TellorMiner#259]
When running on rinkeby, Miners will fail to submit a few times then shut down. 
Failed submissions return errors "Problem submitting solution: replacement transaction underpriced" or "nonce too low"

Most times the miner will recover from these errors and submit successfully, but sometimes this causes the miner to shut itself down for too many failed attempts.

**Comment by krasi-georgiev** [comment]
Thanks for the report. I think @themandalore mentioned that this is due to some infura API calls count restrictions so until it is fixed as a workaround you can try using more than one infura API key.

**Comment by Spuddyminer** [comment]
Thanks for the tip! I will make some more projects in the infura account. (currently using just 2)

**Comment by themandalore** [comment]
Let me know if it's just an API issue...you're probably getting problems using the same infura key for each project
