### ISSUE TITLE
rinkeby / mainnet dataServers on same machine: ListenAndServe()...address already in use

### ISSUE THREAD

**Issue by Spuddyminer** [tellor-io/TellorMiner#265]
Attempting to run two dataservers on the same machine results in:
ListenAndServe(): listen tcp XXX.0.0.X:XXXX: bind: address already in use

For the purposes of testing and mining on the main-net, it would be great if both could be done easily at the same time!

**Comment by krasi-georgiev** [comment]
just had a quick look and you can specify different ports for each instance via the `serverPort` option in the `config.json`
Please reopen if this doesn't answer your questions.
