### ISSUE TITLE
Miner measure

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TellorMiner#46]
Hashrate
Performance (Tokens Mined)
Costs (ETH spent)
Failed txn count

**Comment by mikeghen** [comment]
I'm going to look into logging some stats on the hash rate. I found this place in the code where it might make sense to measure it: https://github.com/tellor-io/TellorMiner/blob/e9eb6811a597221c4c3f098663a9b2f80c0d4f15/pow/powWorker.go#L266

Inside `solveChallenge` there is that four loop. I was thinking of marking the time before the loop starts and then using `i` to keep track of the number of cycles, when it finds a solution or when it just stops (challenge changes). I could mark time again and use  i / the time delta to get cycles per second and just log that out.  

Do you think that could work? Any references for how I could mark start and end time?

**Comment by mikeghen** [comment]
P.S. if someone could point out where those other metrics are in the codebase, I can take a look at surfacing those as well.

**Comment by milkyklim** [comment]
Is there any progress on this one? I am particularly interested in hashrate. 
cc @mikeghen
