### ISSUE TITLE
Smarter tipping

### ISSUE THREAD

**Issue by banteg** [tellor-io/TellorMiner#56]
Currently almost no one uses tipping because the implementation is wasteful. Here is how it can be improved.
- [ ] add a separate option for `tipGasMultiplier`
- [ ] send tips only after `NewValue` event is received
- [ ] allow specifying multiple ids to request, they can be requested in a random or round robin manner
- [ ] implement tippingInterval so the tips are sent every N blocks to reduce the gas costs even further

**Comment by themandalore** [comment]
I think we'll just move to the assigned PSR's.  And with gas costs back in line it seems like much less of an issue.  And even continuing it further, I hope that tipping becomes a non-Issue once parties are actually requesting data
