### ISSUE TITLE
Create Tests

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TellorMiner#6]
Refactor for single purpose components
100% test coverage of all components/ modules

**Comment by krasi-georgiev** [comment]
100% is probably not necessary, but something like 60-70% is more practical.

Another important change would be enabling race detection and goroutine leaks globally for all tests.

**Comment by krasi-georgiev** [comment]
I think we should close this issue in favor of creating some more specific issues for e2e tests that we need to add for each desired behavior of each component.

Feel free to reopen if you had something else in mind with this issue and can add some more details.
