### ISSUE TITLE
Check values before adding them to database

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TellorMiner#70]
If a value changes by more than X%, it shouldn't change it....add in a way that if it happens twice, then its ok.  

The reason for this is that several API failures have happened, so we should check a few times to make sure its not an outlier

**Comment by lodainn** [comment]
If this is happening, it would also make sense to handle a miner startup condition, i.e. never submit the first API call result until it is confirmed by a second.

**Comment by milkyklim** [comment]
@themandalore I want to bring your attention to this issue, again. 

Tracking the values submission and disputes count I can clearly see people are\could be slashed time-to-time. It happens often enough (+ done by different people) to suspect that there might be some sort of race condition in the code.

**Comment by themandalore** [comment]
Thanks @milkyklim , testing a fix now (you can look at the PSRupdate branch to see what I changed.  We were adding zero values that weren't correct, so we now just skip them if the API call fails (which it does sometimes)
