### ISSUE TITLE
Infura rate limits

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TellorMiner#74]

**Comment by mikeghen** [comment]
@themandalore, I updated my config to use `"miningInterruptCheckInterval": 30`, looks like default was 15 seconds. I'm going to let this run a few days and let you know how it goes. I expect it should cut requests to Infura in half, but I guess theres a risk it could cause invalid submissions. What do you think?

**Comment by themandalore** [comment]
It should help, but we're trying to optimize so each core isn't checking anything...should be updated next week sometime so it shouldn't matter how many numProcesses you have running

**Comment by mikeghen** [comment]
Great, just confirmed it did cut the number of infura requests in half by going to 30, though i did have an invalid submission last night when this was running, but to be fair, I've been seeing invalid submissions even with the default `miningInterruptCheckInterval`
